"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', cast=bool)

# Temporary: enable edit flow tracing (structured logging only). Set to True to trace ProductUpdateView.
# Ensure LOGGING config includes logger "edit_trace" at DEBUG level to see TRACE output.
DEBUG_TRACE = config('DEBUG_TRACE', default=False, cast=bool)

# Parse ALLOWED_HOSTS from environment variable (strip surrounding quotes per value)
ALLOWED_HOSTS_STR = config('ALLOWED_HOSTS')
ALLOWED_HOSTS = [
    host.strip().strip("'\"") for host in ALLOWED_HOSTS_STR.split(',') if host.strip()
]
if DEBUG:
    # In development, allow any host (browser may send Host: localhost:8000)
    ALLOWED_HOSTS = ['*']
else:
    # Ensure common dev hosts are allowed even when DEBUG is False (e.g. local runserver)
    for h in ('localhost', '127.0.0.1', '*'):
        if h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(h)


# Application definition

INSTALLED_APPS = [
    'storages',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'app.middleware.DebugTraceMiddleware',  # STEP 4: force_debug_cursor when DEBUG_TRACE
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.EnsureGuestSessionMiddleware',  # Ensure session_key for guest cart/wishlist
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.site_contact_context',
                'app.context_processors.cart_context',
                'app.context_processors.wishlist_context',
                'app.context_processors.admin_message_badge',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='5432'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_SECURE = False  # Set True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# Delivery charge: constant ₹80 for all orders (1 rupee to 1 lakh or any amount)
FLAT_DELIVERY_CHARGE = 80
MAX_CART_QTY = 10
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Cache configuration for rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
# Optional: set to True to cache report summary cards (e.g. when using Redis)
# CACHE_REPORT_SUMMARY = False



EMAIL_BACKEND = 'app.email_backend.CustomEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_NOTIFICATION_EMAILS = ['adithyamc@bthinkx.com']

# Site contact (used site-wide: footer, invoice, WhatsApp FAB, etc.)
SITE_PHONE = config("SITE_PHONE", default="+91 62384 39926")
SITE_WHATSAPP = config("SITE_WHATSAPP", default="916238439926")  # No + or spaces for wa.me

# Razorpay Configuration
RZP_CLIENT_ID = config('RZP_CLIENT_ID')
RZP_CLIENT_SECRET = config('RZP_CLIENT_SECRET')

# Shiprocket Configuration
SHIPROCKET_EMAIL = config('SHIPROCKET_EMAIL')
SHIPROCKET_PASSWORD = config('SHIPROCKET_PASSWORD')

# AWS S3 Storage configuration
USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3:
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME")
    # Correct S3 custom domain with region
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    
    # S3 Configuration (No ACLs - rely on bucket policy)
    # Bucket has "BucketOwnerEnforced" which disables ACLs
    base_s3_object_params = {
        'CacheControl': 'max-age=86400',
    }
    # S3 object tags for billing/cost monitoring (applied to every media upload)
    # Optional .env: AWS_S3_TAG_PROJECT, AWS_S3_TAG_APP, AWS_S3_CLIENT_TAG
    _s3_tag_dict = {
        'project': config('AWS_S3_TAG_PROJECT', default='queen-orange'),
        'app': config('AWS_S3_TAG_APP', default='media'),
    }

    AWS_S3_CLIENT_TAG= config('AWS_S3_CLIENT_TAG', default='queen-orange')
    if AWS_S3_CLIENT_TAG:
        _s3_tag_dict['client'] = AWS_S3_CLIENT_TAG
    from s3_tagging_utils import build_safe_tags
    _s3_tagging_str = build_safe_tags(_s3_tag_dict)
    if _s3_tagging_str:
        base_s3_object_params['Tagging'] = _s3_tagging_str

    AWS_S3_OBJECT_PARAMETERS = base_s3_object_params
    AWS_DEFAULT_ACL = None  # Don't use ACLs, bucket policy handles public access
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    
    # Django 4.2+ STORAGES setting
    # Only media files go to S3; static files are always served locally
    STORAGES = {
        "default": {
            "BACKEND": "custom_storage.MediaFileStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    # Public base URL for media files in S3:
    # files will be stored under: queen-orange/media/<upload_to>/<filename>
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/queen-orange/media/"
else:
    # Local file storage for everything
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"

